#!/usr/bin/env bash

DIR=$(dirname $BASH_SOURCE)

if [[ $1 = "update" ]] | [[ $1 = "install" ]]; then
    $DIR/scripts/update.sh $DIR
else
    FLASK_APP=$DIR/app flask db upgrade -d $DIR/migrations
    gunicorn app:app -b :$(python3 $DIR/scripts/get-port.py) --chdir $DIR -w 4
fi
