"""Add relative column priorities

Revision ID: 16942fdb0f18
Revises: 6286ef6698f9
Create Date: 2022-12-11 16:39:27.834743

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "16942fdb0f18"
down_revision = "6286ef6698f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset_column", schema=None) as batch_op:
        batch_op.add_column(sa.Column("priority", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset_column", schema=None) as batch_op:
        batch_op.drop_column("priority")

    # ### end Alembic commands ###
