"""Rename priority column to order

Revision ID: 5e7f3be664d5
Revises: 16942fdb0f18
Create Date: 2022-12-19 18:53:56.967109

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5e7f3be664d5"
down_revision = "16942fdb0f18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset_column", schema=None) as batch_op:
        batch_op.add_column(sa.Column("order", sa.Integer(), nullable=True))
        batch_op.drop_column("priority")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset_column", schema=None) as batch_op:
        batch_op.add_column(sa.Column("priority", sa.INTEGER(), nullable=True))
        batch_op.drop_column("order")

    # ### end Alembic commands ###
